### PR TITLE
[v0.5.0] Improvements on processor and support to FragmentFactory

### LINKED ISSUE #17: Wrong paths with multi-application modules
I've two application modules, `app_a_app` and `app_b_app`. And feature modules like `app_a_payment` and `app_b_payment`. These specific modules inherit from an common scope module like `payment`.

In specific feature modules (by app), always the activity have the same name and the same EntryFlowNav like `PayersActivity`. 

So my module router do the maginc (with this cool library) calling the right path. Like `start(FEATURE_X)` inside a extension function like `openFeatureX()`.

When I'm running the app, the entrymap generated by library it's mixing paths from feature modules from other application module. 

E.g.:

[1] `br.com.app_a.ScreenCool`
[2] `br.com.app_b.ScreenCool`

I'm seeing references/paths in wrong application, causing `ActivityNotFoundException`.

### PR DESCRIPTION
**Pull request by jeziellago**
- Add support to `FragmentFactory` 🚀 
- Fix proguard/R8 errors
- Fix #17 
- Migrate from Travis to Github Actions

### CODE REVIEW

File: processor/src/main/java/com/flownav/processor/FlowNavActionsBuilder.kt [hunk 1]
```diff
@@ -53,18 +55,28 @@ class FlowNavActionsBuilder(
...
+    private fun createEntryConfig(
+        action: String,
+        actionType: String,
+        idReference: String? = null
+    ): String = if (idReference != null) {
+        "this[\"$action\"] = EntryConfig(${actionType}::class.java.name, R.id.${idReference})"
+    } else {
+        "this[\"$action\"] = EntryConfig(${actionType}::class.java.name)"
+    }
+
```
Comment (AlexSoaresDeSiqueira) [inline processor/src/main/java/com/flownav/processor/FlowNavActionsBuilder.kt:79]: gostei
